'use client';

import { ArrowRight, CheckCircle2, CircleAlert, FileImage, Image, Map, MessageCircleQuestion, PenLine, Settings2 } from 'lucide-react';
import Link from 'next/link';
import { STUDIO_CATEGORIES, STUDIO_TOOLS, toolsForCategory, type StudioCategory } from '@/config/studio-tools';

const ICONS = { Understand: MessageCircleQuestion, Create: PenLine, Media: Image, Visualize: Map, Utilities: Settings2 } satisfies Record<StudioCategory, typeof MessageCircleQuestion>;

export function StudioDashboardPage() {
  return <section className="mx-auto min-h-full max-w-6xl p-4 sm:p-6 lg:p-8" aria-labelledby="studio-dashboard-title"><div className="border-b border-border pb-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">AI Workspace</p><h1 id="studio-dashboard-title" className="mt-2 text-3xl font-semibold tracking-[-0.04em]">AI Studio</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">All registered AI capabilities, grouped by what you want to understand, create, transform, visualize, or support.</p></div><div className="mt-8 space-y-8">{STUDIO_CATEGORIES.map((category) => { const CategoryIcon = ICONS[category]; return <section key={category} aria-labelledby={`studio-dashboard-${category}`}><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary"><CategoryIcon className="size-4" /></span><div><h2 id={`studio-dashboard-${category}`} className="text-sm font-semibold">{category}</h2><p className="text-xs text-muted-foreground">{categoryDescription(category)}</p></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{toolsForCategory(category).map((tool) => <article key={tool.id} className="flex min-h-32 flex-col rounded-2xl border border-border bg-panel p-4"><div className="flex items-start justify-between gap-2"><div className="flex items-center gap-2"><FileImage className="size-4 text-primary" /><h3 className="text-xs font-semibold">{tool.name}</h3></div><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] font-semibold ${tool.availability === 'available' ? 'bg-emerald-500/10 text-emerald-700' : 'bg-amber-500/10 text-amber-700'}`}>{tool.availability === 'available' ? <CheckCircle2 className="size-3" /> : <CircleAlert className="size-3" />}{tool.availability === 'available' ? 'Available' : 'Backend gap'}</span></div><p className="mt-3 flex-1 text-[11px] leading-5 text-muted-foreground">{tool.description}</p>{tool.availability === 'missing' && <p className="mb-3 text-[10px] leading-4 text-amber-700">{tool.missingReason}</p>}{tool.availabilityNote && <p className="mb-3 text-[10px] leading-4 text-muted-foreground">{tool.availabilityNote}</p>}<Link href={tool.availability === 'available' ? `/workspace?panel=studio&tool=${tool.id}` : '#'} aria-disabled={tool.availability === 'missing'} className={`inline-flex items-center gap-1 text-[11px] font-semibold ${tool.availability === 'available' ? 'text-primary hover:underline' : 'cursor-not-allowed text-muted-foreground'}`}>{tool.availability === 'available' ? 'Open tool' : 'Unavailable'}{tool.availability === 'available' && <ArrowRight className="size-3.5" />}</Link></article>)}</div></section>; })}</div></section>;
}

function categoryDescription(category: StudioCategory) {
  return { Understand: 'Ask, explain, summarize, and translate.', Create: 'Turn workspace material into useful artifacts.', Media: 'Generate or transform visual, audio, and video media.', Visualize: 'See relationships, trends, and structure.', Utilities: 'Supporting tools for grounded workspace work.' }[category];
}
