import Link from 'next/link';
import { ArrowRight, BookOpen, Check, FileText, Sparkles, WandSparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Brand } from '@/components/layout/brand';
import { ThemeToggle } from '@/components/layout/theme-toggle';

const features = [
  { icon: FileText, title: 'Bring your sources', description: 'Upload documents, keep them organized, and make every answer traceable.' },
  { icon: Sparkles, title: 'Ask with confidence', description: 'Chat with your workspace and follow grounded answers back to the source.' },
  { icon: WandSparkles, title: 'Create with AI Studio', description: 'Turn research into summaries, reports, mind maps, translations, and more.' },
];

export function LandingPage() {
  return <div className="min-h-dvh overflow-hidden bg-background text-foreground">
    <header className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/" aria-label="29 AI Workspace home"><Brand /></Link><div className="flex items-center gap-2"><ThemeToggle /><Link href="/login" className="hidden rounded-lg px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-foreground sm:inline-flex">Sign in</Link><Button asChild size="sm"><Link href="/register">Get started</Link></Button></div></header>
    <main>
      <section className="mx-auto grid max-w-7xl items-center gap-12 px-4 pb-16 pt-12 sm:px-6 sm:pt-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-24 lg:pt-24">
        <div><p className="inline-flex items-center gap-2 rounded-full border border-border bg-panel px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[0.16em] text-primary"><span className="size-1.5 rounded-full bg-primary" /> One focused workspace</p><h1 className="mt-6 max-w-3xl text-4xl font-semibold tracking-[-0.06em] sm:text-6xl lg:text-7xl">Your thinking, <span className="text-primary">with room to grow.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">29 AI Workspace brings your sources, conversations, and AI creation tools into one calm place to learn, research, and make progress.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="md"><Link href="/register">Create your workspace <ArrowRight aria-hidden="true" className="size-4" /></Link></Button><Link href="/login" className="inline-flex h-10 items-center justify-center rounded-lg border border-border bg-panel px-4 text-sm font-medium hover:bg-accent">Sign in to continue</Link></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Check aria-hidden="true" className="size-3.5 text-primary" /> Source-grounded chat</span><span className="inline-flex items-center gap-1.5"><Check aria-hidden="true" className="size-3.5 text-primary" /> AI Studio creation tools</span><span className="inline-flex items-center gap-1.5"><Check aria-hidden="true" className="size-3.5 text-primary" /> Your themes, your way</span></div></div>
        <div className="relative"><div className="absolute -inset-10 rounded-full bg-primary/10 blur-3xl" /><div className="relative rounded-[2rem] border border-border bg-panel p-3 shadow-[0_30px_100px_-50px_var(--primary)]"><div className="rounded-[1.5rem] border border-border bg-background p-4 sm:p-6"><div className="flex items-center justify-between border-b border-border pb-4"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-primary/10 text-primary"><Sparkles className="size-4" /></span><span className="text-sm font-semibold">Research workspace</span></div><span className="rounded-full bg-muted px-2 py-1 text-[10px] text-muted-foreground">Live</span></div><div className="grid gap-3 py-5 sm:grid-cols-[.8fr_1.2fr]"><div className="rounded-xl border border-border bg-panel p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">Sources</p><div className="mt-4 space-y-2"><div className="flex items-center gap-2 rounded-lg bg-muted p-2 text-xs"><FileText className="size-3.5 text-primary" /> Research notes</div><div className="flex items-center gap-2 rounded-lg bg-muted p-2 text-xs"><BookOpen className="size-3.5 text-primary" /> Product brief</div><div className="flex items-center gap-2 rounded-lg bg-muted p-2 text-xs"><FileText className="size-3.5 text-primary" /> Interview.md</div></div></div><div className="rounded-xl border border-border bg-panel p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">Conversation</p><div className="mt-5 space-y-4"><div className="ml-auto h-7 w-3/4 rounded-xl rounded-br-sm bg-primary/15" /><div className="h-12 w-[92%] rounded-xl rounded-bl-sm bg-muted" /><div className="h-7 w-1/2 rounded-xl rounded-bl-sm bg-muted" /></div><div className="mt-6 h-9 rounded-lg border border-border bg-background" /></div></div></div></div></div>
      </section>
      <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8"><div className="grid gap-3 md:grid-cols-3">{features.map((feature) => <article key={feature.title} className="rounded-2xl border border-border bg-panel p-5"><span className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary"><feature.icon aria-hidden="true" className="size-4" /></span><h2 className="mt-5 text-sm font-semibold">{feature.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{feature.description}</p></article>)}</div></section>
    </main>
    <footer className="mx-auto flex max-w-7xl items-center justify-between border-t border-border px-4 py-6 text-[11px] text-muted-foreground sm:px-6 lg:px-8"><span>29 AI Workspace</span><span>Built for thoughtful work.</span></footer>
  </div>;
}
