import { Injectable } from '@nestjs/common';
import * as crypto from 'crypto';
import {
  ChatCompletionResult,
  ChatMessageInput,
  EMBEDDING_DIMENSIONS,
  LlmProvider,
} from '../interfaces/llm-provider.interface';

/**
 * Deterministic, dependency-free "LLM" so the whole pipeline (RAG, summaries,
 * diagrams, chat) runs end-to-end without any API keys. It doesn't call out
 * to the network - every other provider falls back to this one automatically
 * when its API key isn't configured (see LlmGatewayService).
 */
@Injectable()
export class MockLlmProvider implements LlmProvider {
  readonly key = 'mock';
  readonly displayName = 'Mock LLM (offline)';
  readonly model = 'mock-1';

  isConfigured(): boolean {
    return true;
  }

  chat(messages: ChatMessageInput[]): Promise<ChatCompletionResult> {
    const lastUser = [...messages].reverse().find((m) => m.role === 'user');
    const systemPrompt = messages.find((m) => m.role === 'system')?.content;

    const content = this.buildResponse(lastUser?.content ?? '', systemPrompt);

    return Promise.resolve({ content, provider: this.key, model: this.model });
  }

  embed(text: string): Promise<number[]> {
    // Deterministic pseudo-embedding: hash the text into a seed, then expand
    // it into a unit vector. Same input -> same vector, so cosine similarity
    // between related mock-embedded chunks is still meaningful for testing
    // the RAG pipeline end-to-end (though not semantically as good as a real model).
    const hash = crypto.createHash('sha256').update(text).digest();
    const vector: number[] = [];
    let seed = hash.readUInt32BE(0);

    for (let i = 0; i < EMBEDDING_DIMENSIONS; i++) {
      seed = (seed * 1103515245 + 12345) & 0x7fffffff;
      vector.push((seed / 0x7fffffff) * 2 - 1);
    }

    const norm = Math.sqrt(vector.reduce((sum, v) => sum + v * v, 0));
    return Promise.resolve(vector.map((v) => v / (norm || 1)));
  }

  private buildResponse(question: string, systemPrompt?: string): string {
    if (systemPrompt?.includes('MERMAID')) {
      const diagramType =
        systemPrompt.match(/Mermaid\.js "([^"]+)"/)?.[1] ?? 'flowchart';

      if (diagramType === 'sequenceDiagram') {
        return [
          '```mermaid',
          'sequenceDiagram',
          '    participant U as User',
          '    participant A as AI Document Assistant',
          '    U->>A: Upload document',
          '    A-->>U: Extract, index, and analyze content',
          '```',
        ].join('\n');
      }

      if (diagramType === 'classDiagram') {
        return [
          '```mermaid',
          'classDiagram',
          '    class Document {',
          '      +string originalName',
          '      +string extractedText',
          '    }',
          '    class DocumentSummary',
          '    class DocumentDiagram',
          '    Document "1" --> "*" DocumentSummary',
          '    Document "1" --> "*" DocumentDiagram',
          '```',
        ].join('\n');
      }

      if (diagramType === 'mindmap') {
        return [
          '```mermaid',
          'mindmap',
          '  root((Document))',
          '    Upload',
          '    Text extraction',
          '    RAG retrieval',
          '    AI analysis',
          '```',
        ].join('\n');
      }

      return [
        '```mermaid',
        'flowchart TD',
        '    A[Document uploaded] --> B[Text extracted & chunked]',
        '    B --> C[Chunks embedded]',
        '    C --> D[Relevant chunks retrieved]',
        '    D --> E[LLM generates answer]',
        '```',
      ].join('\n');
    }

    if (systemPrompt?.includes('SUMMARY')) {
      return (
        'This is a placeholder summary generated by the offline mock LLM provider. ' +
        'Configure a real provider (OPENAI_API_KEY, GEMINI_API_KEY, ANTHROPIC_API_KEY, ' +
        'or LLAMA_API_URL/LLAMA_API_KEY) in your .env to get real summaries.'
      );
    }

    return (
      `[mock-llm] I received your question: "${question.slice(0, 200)}". ` +
      'This is a deterministic offline response used while no real LLM provider ' +
      'is configured - the RAG context you supplied was received correctly. ' +
      'Add an API key for GPT, Gemini, Claude, or Llama in your .env and the ' +
      'gateway will route to it automatically instead of this mock.'
    );
  }
}
