'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '@/lib/api-client';
import { useHasSession } from '@/features/sources/hooks/use-sources';
import type { Collection, Favorite, OutputVersion, Preference, SavedSearch, SearchResult, Tag } from '../knowledge-types';

export function useCollections(workspaceId: string | null) { const hasSession = useHasSession(); return useQuery({ queryKey: ['collections', workspaceId], queryFn: () => apiRequest<Collection[]>(`/collections?workspaceId=${workspaceId}`), enabled: Boolean(workspaceId) && hasSession }); }
export function useCollectionActions(workspaceId: string | null) { const client = useQueryClient(); const refresh = () => client.invalidateQueries({ queryKey: ['collections', workspaceId] }); return {
  create: useMutation({ mutationFn: (body: { name: string; parentId?: string }) => apiRequest('/collections', { method: 'POST', body: JSON.stringify({ workspaceId, ...body }) }), onSuccess: refresh }),
  update: useMutation({ mutationFn: ({ id, ...body }: { id: string; name?: string; parentId?: string | null; position?: number }) => apiRequest(`/collections/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), onSuccess: refresh }),
  remove: useMutation({ mutationFn: (id: string) => apiRequest(`/collections/${id}`, { method: 'DELETE' }), onSuccess: refresh }),
}; }
export function useTags(workspaceId: string | null) { const hasSession = useHasSession(); return useQuery({ queryKey: ['tags', workspaceId], queryFn: () => apiRequest<Tag[]>(`/tags?workspaceId=${workspaceId}`), enabled: Boolean(workspaceId) && hasSession }); }
export function useTagActions(workspaceId: string | null) { const client = useQueryClient(); const refresh = () => client.invalidateQueries({ queryKey: ['tags', workspaceId] }); return { create: useMutation({ mutationFn: (name: string) => apiRequest('/tags', { method: 'POST', body: JSON.stringify({ workspaceId, name }) }), onSuccess: refresh }), update: useMutation({ mutationFn: ({ id, name }: { id: string; name: string }) => apiRequest(`/tags/${id}`, { method: 'PATCH', body: JSON.stringify({ name }) }), onSuccess: refresh }), remove: useMutation({ mutationFn: (id: string) => apiRequest(`/tags/${id}`, { method: 'DELETE' }), onSuccess: refresh }) }; }
export function useFavorites(workspaceId: string | null) { const hasSession = useHasSession(); return useQuery({ queryKey: ['favorites', workspaceId], queryFn: () => apiRequest<Favorite[]>(`/favorites?workspaceId=${workspaceId}`), enabled: Boolean(workspaceId) && hasSession }); }
export function useFavoriteToggle(workspaceId: string | null) { const client = useQueryClient(); const refresh = () => client.invalidateQueries({ queryKey: ['favorites', workspaceId] }); return { add: useMutation({ mutationFn: (target: { sourceId?: string; outputId?: string }) => apiRequest('/favorites', { method: 'POST', body: JSON.stringify({ workspaceId, ...target }) }), onSuccess: refresh }), remove: useMutation({ mutationFn: (id: string) => apiRequest(`/favorites/${id}`, { method: 'DELETE' }), onSuccess: refresh }) }; }
export function usePreferences(workspaceId: string | null) { const hasSession = useHasSession(); return useQuery({ queryKey: ['preferences', workspaceId], queryFn: () => apiRequest<Preference>(`/preferences?workspaceId=${workspaceId}`), enabled: Boolean(workspaceId) && hasSession }); }
export function useUpdatePreferences(workspaceId: string | null) { const client = useQueryClient(); return useMutation({ mutationFn: (value: Partial<Preference>) => apiRequest<Preference>('/preferences', { method: 'PATCH', body: JSON.stringify({ workspaceId, ...value }) }), onSuccess: (value) => client.setQueryData(['preferences', workspaceId], value) }); }
export function useOutputVersions(outputId: string | null) { const hasSession = useHasSession(); return useQuery({ queryKey: ['output-versions', outputId], queryFn: () => apiRequest<OutputVersion[]>(`/outputs/${outputId}/versions`), enabled: Boolean(outputId) && hasSession }); }
export function useSearch(workspaceId: string | null, query: string, enabled = true, mode: 'lexical' | 'semantic' | 'hybrid' = 'hybrid') { const hasSession = useHasSession(); return useQuery({ queryKey: ['global-search', workspaceId, query, mode], queryFn: () => apiRequest<SearchResult>(`/search?workspaceId=${workspaceId}&query=${encodeURIComponent(query)}&mode=${mode}`), enabled: enabled && Boolean(workspaceId) && Boolean(query.trim()) && hasSession, staleTime: 15_000 }); }
export function useSavedSearches(workspaceId: string | null) { const hasSession = useHasSession(); return useQuery({ queryKey: ['saved-searches', workspaceId], queryFn: () => apiRequest<SavedSearch[]>(`/search/saved?workspaceId=${workspaceId}`), enabled: Boolean(workspaceId) && hasSession }); }
export function useSavedSearchActions(workspaceId: string | null) { const client = useQueryClient(); const refresh = () => client.invalidateQueries({ queryKey: ['saved-searches', workspaceId] }); return {
  create: useMutation({ mutationFn: (body: { name: string; query: string; tagId?: string }) => apiRequest<SavedSearch>('/search/saved', { method: 'POST', body: JSON.stringify({ workspaceId, ...body }) }), onSuccess: refresh }),
  remove: useMutation({ mutationFn: (id: string) => apiRequest(`/search/saved/${id}`, { method: 'DELETE' }), onSuccess: refresh }),
}; }
