ALTER TYPE "AIOutputType" ADD VALUE IF NOT EXISTS 'FLASHCARDS';
ALTER TYPE "AIOutputType" ADD VALUE IF NOT EXISTS 'QUIZ';
ALTER TYPE "AIOutputType" ADD VALUE IF NOT EXISTS 'STUDY_GUIDE';
ALTER TYPE "AIOutputType" ADD VALUE IF NOT EXISTS 'ANALYTICS_REPORT';
ALTER TYPE "AIOutputType" ADD VALUE IF NOT EXISTS 'CHART';
