'use client';
import { Boxes, ChevronRight, Folder, GripVertical, Pencil, Plus, Tag as TagIcon, Trash2 } from 'lucide-react';
import { useMemo, useState, type DragEvent, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { useWorkspaceStore } from '@/stores/workspace-store';
import { useCollectionActions, useCollections, useTagActions, useTags } from '../hooks/use-knowledge';
import type { Collection } from '../knowledge-types';

export function CollectionsPageContent() {
  const workspaceId = useWorkspaceStore((state) => state.activeWorkspaceId);
  const collections = useCollections(workspaceId); const actions = useCollectionActions(workspaceId);
  const tags = useTags(workspaceId); const tagActions = useTagActions(workspaceId);
  const [name, setName] = useState(''); const [tagName, setTagName] = useState(''); const [selected, setSelected] = useState<string | null>(null);
  const roots = useMemo(() => (collections.data ?? []).filter((item) => !item.parentId), [collections.data]);
  const create = (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; actions.create.mutate({ name: name.trim(), parentId: selected ?? undefined }, { onSuccess: () => setName('') }); };
  const drop = (event: DragEvent, parentId: string | null) => { event.preventDefault(); const id = event.dataTransfer.getData('text/collection-id'); if (id && id !== parentId) actions.update.mutate({ id, parentId }); };
  const render = (item: Collection, depth = 0): React.ReactNode => { const children = (collections.data ?? []).filter((child) => child.parentId === item.id); return <li key={item.id}><div draggable onDragStart={(event) => event.dataTransfer.setData('text/collection-id', item.id)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(event, item.id)} className={`group flex items-center gap-2 rounded-lg px-2 py-2 ${selected === item.id ? 'bg-primary/10 text-primary' : 'hover:bg-accent'}`} style={{ paddingLeft: `${8 + depth * 18}px` }}><GripVertical className="size-3.5 cursor-grab text-muted-foreground" aria-hidden="true"/><button className="flex min-w-0 flex-1 items-center gap-2 text-left text-sm" onClick={() => setSelected(item.id)}><ChevronRight className={`size-3 transition ${children.length ? '' : 'invisible'}`}/><Folder className="size-4"/><span className="truncate">{item.name}</span><span className="ml-auto text-[10px] text-muted-foreground">{item._count.items}</span></button><Button variant="ghost" size="icon" aria-label={`Rename ${item.name}`} onClick={() => { const next = window.prompt('Collection name', item.name); if (next?.trim()) actions.update.mutate({ id: item.id, name: next.trim() }); }}><Pencil className="size-3.5"/></Button><Button variant="ghost" size="icon" aria-label={`Delete ${item.name}`} onClick={() => window.confirm(`Delete ${item.name} and nested collections?`) && actions.remove.mutate(item.id)}><Trash2 className="size-3.5"/></Button></div>{children.length > 0 && <ul>{children.map((child) => render(child, depth + 1))}</ul>}</li>; };
  return <section className="mx-auto min-h-full max-w-7xl p-4 sm:p-6 lg:p-8" aria-labelledby="collections-title"><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Knowledge workspace</p><h1 id="collections-title" className="mt-2 text-3xl font-semibold tracking-tight">Collections</h1><p className="mt-1 text-sm text-muted-foreground">Nest and move collections; a source or output can live in more than one.</p></div>
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="rounded-2xl border border-border bg-panel p-4"><form onSubmit={create} className="flex gap-2"><label className="sr-only" htmlFor="new-collection">Collection name</label><input id="new-collection" value={name} onChange={(event) => setName(event.target.value)} placeholder={selected ? 'New nested collection' : 'New collection'} className="h-10 min-w-0 flex-1 rounded-lg border border-border bg-background px-3 text-sm"/><Button type="submit" disabled={!workspaceId || actions.create.isPending}><Plus className="size-4"/>Create</Button></form><div onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(event, null)} className="mt-4 min-h-72 rounded-xl border border-dashed border-border p-2"><ul aria-label="Collection tree">{roots.map((item) => render(item))}</ul>{!collections.isLoading && !roots.length && <div className="grid min-h-64 place-items-center text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><Boxes className="size-5"/></span><h2 className="mt-3 text-sm font-semibold">No collections yet</h2><p className="mt-1 text-xs text-muted-foreground">Create one to organize sources and AI outputs.</p></div></div>}</div></div>
      <aside className="rounded-2xl border border-border bg-panel p-4" aria-labelledby="tags-title"><div className="flex items-center gap-2"><TagIcon className="size-4 text-primary"/><h2 id="tags-title" className="font-semibold">Tags</h2></div><form className="mt-4 flex gap-2" onSubmit={(event) => { event.preventDefault(); if (tagName.trim()) tagActions.create.mutate(tagName.trim(), { onSuccess: () => setTagName('') }); }}><input aria-label="New tag name" value={tagName} onChange={(event) => setTagName(event.target.value)} className="h-9 min-w-0 flex-1 rounded-lg border border-border bg-background px-3 text-xs" placeholder="Add tag"/><Button size="sm">Add</Button></form><ul className="mt-4 space-y-2">{tags.data?.map((tag) => <li key={tag.id} className="flex items-center gap-2 rounded-lg border border-border bg-background px-3 py-2"><span className="size-2.5 rounded-full bg-primary" style={tag.color ? { backgroundColor: tag.color } : undefined}/><span className="min-w-0 flex-1 truncate text-xs">{tag.name}</span><span className="text-[10px] text-muted-foreground">{tag._count.assignments}</span><button aria-label={`Rename tag ${tag.name}`} onClick={() => { const next = window.prompt('Tag name', tag.name); if (next?.trim()) tagActions.update.mutate({ id: tag.id, name: next.trim() }); }}><Pencil className="size-3.5"/></button><button aria-label={`Delete tag ${tag.name}`} onClick={() => tagActions.remove.mutate(tag.id)}><Trash2 className="size-3.5"/></button></li>)}</ul></aside></div></section>;
}
