'use client';

import { CheckCircle2, CircleAlert, HeartPulse, KeyRound, RefreshCw, Settings2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useProviderCatalog } from '../hooks/use-provider-catalog';
import { usePreferences } from '@/features/knowledge/hooks/use-knowledge';
import { useWorkspaceStore } from '@/stores/workspace-store';

export function AiProviderSettingsPage() {
  const workspaceId = useWorkspaceStore((state) => state.activeWorkspaceId);
  const preferences = usePreferences(workspaceId);
  const catalog = useProviderCatalog();
  const healthRows = catalog.health.data?.providers ?? [];

  return <section className="mx-auto min-h-full max-w-5xl p-4 sm:p-6 lg:p-8" aria-labelledby="provider-settings-title">
    <div className="flex flex-col justify-between gap-4 border-b border-border pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">AI configuration</p><div className="mt-2 flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Settings2 className="size-5" /></span><div><h1 id="provider-settings-title" className="text-2xl font-semibold tracking-[-0.03em] sm:text-3xl">AI Provider Settings</h1><p className="mt-1 text-sm leading-6 text-muted-foreground">Every provider stays visible. Configure credentials to make its models available.</p></div></div></div><Button variant="outline" onClick={() => void catalog.health.refetch()} disabled={catalog.health.isFetching}><RefreshCw className={catalog.health.isFetching ? 'size-4 animate-spin' : 'size-4'} /> Run health check</Button></div>
    {catalog.providers.isError && <p role="alert" className="mt-5 rounded-xl bg-red-500/10 p-3 text-xs text-red-700">Provider catalog could not be loaded.</p>}
    <div className="mt-6 grid gap-4 lg:grid-cols-2">{(catalog.providers.data ?? []).map((provider) => { const health = healthRows.find((item) => item.id === provider.id); const configured = provider.configured; const models = catalog.models.data?.filter((item) => item.provider === provider.id) ?? []; return <article key={provider.id} className="rounded-2xl border border-border bg-panel p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">{provider.name}</h2><p className="mt-1 text-[11px] text-muted-foreground">{provider.id}</p></div><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] font-semibold ${configured ? 'bg-emerald-500/10 text-emerald-700' : 'bg-muted text-muted-foreground'}`}>{configured ? <CheckCircle2 className="size-3" /> : <CircleAlert className="size-3" />}{configured ? 'Configured' : 'Not Configured'}</span></div><dl className="mt-5 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted-foreground">API key configured</dt><dd className="mt-1 font-medium">{health?.apiKeyConfigured || configured ? 'Yes' : 'No'}</dd></div><div><dt className="text-muted-foreground">Health check</dt><dd className="mt-1 font-medium">{health?.status === 'ready' ? 'Ready' : 'Not Configured'}</dd></div><div><dt className="text-muted-foreground">Default model</dt><dd className="mt-1 truncate font-medium">{preferences.data?.defaultProvider === provider.id ? preferences.data.defaultModel : health?.defaultModel ?? provider.models[0] ?? '—'}</dd></div><div><dt className="text-muted-foreground">Available models</dt><dd className="mt-1 font-medium">{models.length || provider.models.length}</dd></div></dl><div className="mt-4 rounded-xl border border-border bg-background p-3"><p className="flex items-center gap-1.5 text-[11px] font-semibold"><KeyRound className="size-3.5 text-primary" /> Models</p><ul className="mt-2 space-y-1 text-[11px] text-muted-foreground">{(models.length ? models : provider.models.map((id) => ({ id, name: id }))).map((model) => <li key={model.id} className="flex items-center justify-between gap-2"><span className="truncate">{model.name}</span><span>{configured ? 'Available' : 'Not Configured'}</span></li>)}</ul></div></article>; })}</div>
    {!catalog.providers.isLoading && !catalog.providers.data?.length && <div className="mt-6 rounded-2xl border border-dashed border-border p-8 text-center text-xs text-muted-foreground">No provider catalog entries were returned.</div>}
    <div className="mt-6 rounded-2xl border border-border bg-background p-4 text-xs text-muted-foreground"><HeartPulse className="mr-2 inline size-4 text-primary" />Health checks report configuration and catalog readiness. Provider requests remain subject to their own API availability and rate limits.</div>
  </section>;
}
