import type { AnalyticsContent } from '../ai-studio-types';

const number = (value: number | null) => value === null ? '—' : Number(value.toFixed(3)).toLocaleString();

export function AnalyticsDashboard({ report }: { report: AnalyticsContent }) {
  return <section aria-label="Analytics dashboard" className="space-y-4">
    <div className="rounded-xl border border-border bg-background p-4"><h4 className="text-sm font-semibold">Summary</h4><p className="mt-2 text-xs leading-5 text-muted-foreground">{report.summary}</p></div>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[['Rows', report.rowCount], ['Columns', report.columns.length], ['Missing', report.missingValues], ['Duplicates', report.duplicateRows.length]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-background p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>)}</div>
    <div className="overflow-x-auto rounded-xl border border-border bg-background"><table className="w-full min-w-[680px] text-left text-xs"><caption className="p-3 text-left font-semibold">Column statistics</caption><thead className="border-y border-border bg-muted/40"><tr>{['Column', 'Type', 'Count', 'Missing', 'Unique', 'Min', 'Max', 'Mean', 'Median'].map((heading) => <th key={heading} className="p-2 font-medium">{heading}</th>)}</tr></thead><tbody>{report.columns.map((column) => <tr key={column.name} className="border-b border-border last:border-0"><td className="p-2 font-medium">{column.name}</td><td className="p-2">{column.type}</td><td className="p-2">{column.count}</td><td className="p-2">{column.missing}</td><td className="p-2">{column.unique}</td><td className="p-2">{number(column.min)}</td><td className="p-2">{number(column.max)}</td><td className="p-2">{number(column.mean)}</td><td className="p-2">{number(column.median)}</td></tr>)}</tbody></table></div>
    <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-border bg-background p-4"><h4 className="text-xs font-semibold">Trends</h4>{report.trends.length ? <ul className="mt-2 space-y-1 text-xs text-muted-foreground">{report.trends.map((trend) => <li key={trend.column}>{trend.column}: <strong className="text-foreground">{trend.direction}</strong> ({Math.round(trend.change * 100)}%)</li>)}</ul> : <p className="mt-2 text-xs text-muted-foreground">No numeric trends detected.</p>}</div><div className="rounded-xl border border-border bg-background p-4"><h4 className="text-xs font-semibold">Data quality</h4><p className="mt-2 text-xs text-muted-foreground">{report.outliers.length} outliers · {report.correlations.length} numeric correlations · {report.sheetCount} sheet{report.sheetCount === 1 ? '' : 's'}</p></div></div>
  </section>;
}
